### ISSUE TITLE
Class documentation

### ISSUE THREAD

**Issue by sibirrer** [DES-SL/Y6_Bulk_Coadd_Cutouts#1]
https://github.com/DES-SL/Y6_Bulk_Coadd_Cutouts/blob/bbcc77cb8cbbf566d27d2f2abd0918cd4427cfa0/cutout.py#L21

This looks great! Please make sure each class has a dedicated specific role and this role is well documented at the class level and also the __init__() variables are documented.

**Comment by rmorgan10** [comment]
Added documentation in [pull request](https://github.com/DES-SL/Y6_Bulk_Coadd_Cutouts/pull/2)

**Comment by rmorgan10** [comment]
Pull request merged by commit [39ea62d](https://github.com/DES-SL/Y6_Bulk_Coadd_Cutouts/commit/39ea62d5175f8649cb29e11e1ff268b5c1ac1d31)
