### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by kadrlica** [DES-SL/Y6_Bulk_Coadd_Cutouts#22]
@rmorgan10 is the name of this repository correct? The DELVE cutouts are certainly not coming from coadds, and I'm not sure there is anything in the code that makes it coadd-specific.

**Comment by rmorgan10** [comment]
So far this repository was meant for the DES cutouts, and I believe @erikzaborowski is utilizing some of the functionalities for DELVE, but because the focs of this repo was DES I think "Coadd" is okay to have in the name

**Comment by erikzaborowski** [comment]
Yep, this repo is specific to the DES Y6 cutouts. There hasn't been a real need until now (as I've been working on most things by myself), but I am thinking at this point it would make sense to create a DELVE SL repo (or org) and I can host things like the DELVE cutout tool there.

**Comment by kadrlica** [comment]
@erikzaborowski I can add you to the delve-survey github organization if you aren't already.

**Comment by erikzaborowski** [comment]
That would be perfect! I don't think I'm in it currently
