### ISSUE TITLE
Construct path to tile

### ISSUE THREAD

**Issue by rmorgan10** [DES-SL/Y6_Bulk_Coadd_Cutouts#5]
Looks good!

Can this be done without the wildcard character? What information is in the filenames here? If possible, I'd like to fully construct the file path to avoid these errors you raise occurring.

**Comment by jhod0** [comment]
The wildcard is something like the job ID which produced the cutouts. @bechtol said he might have code to provide this, but for now this is a pretty simple solution.

**Comment by rmorgan10** [comment]
Ah gotcha, in that case let's just stick with the glob approach.
